language: node_js
node_js:
- node
after_success:
- npm run coverage
addons:
  chrome: stable
before_script:
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov npm run cover
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: Q3zOe/hgDLRfJRwIapcR4BlZIOCQrAyOMJlPQ4V7zwnb13Dc/pGLvH00WxUaZynyIuRmDnWWGxVjo/mSHEzLk5Ma49C7epsgvOpxhdXoNqExEMqrFaHsmUksusfxCADYJxUZeHowqX54T2CEyoInbjCHDf7kvjuLXqfaBEn07hqIlxmYnDwI0IBu3gocQBrGL0P13T82qzH8oQj0Efrq+gvq2YruN3SmiQef2ges2cftyN51QCbH1gH6rhC2EE3GXH+pblSsVs6xjoW3IUBdsNBLPXWhRtcmt6dzMi6UqB8lZt+sXHBgyF5RB0CJW+2SyCIWXFbBNMRP50HRLJPvgmVEFzNJrZOBJe0PFra/41WOkNcCEBj7OVZ6B91uoRr8OHQtb+8Q4TdaZozw7fE+7a31DmbsSTMV8GypGOAYzIaF5AT11PVeUf52J4RXpIVvOPJPfHTN/y0jqBWYX9bZV5CELWQ6+MQDOH8iVc/50nmDovI6mQg7xU0jJ7KgMdusmwedknFJmYjUjl2ABVFDJpqGMPTq7p4SXE3HvN6/ERdnw7Bv+I6uuwyrKdlHXPbu4fLJ5No5Cweou1jmcYp/T2d7N7F41fyp7xkirBA/aw2AcpDl16v+zmwhgqz/kstVQaYoi3ZEEBBR6tSanukFeLOxPPQ2lijCta6i3L6KZCA=
  app: shrouded-tor-69589
